### PR TITLE
fix(ci): setup updatecli on validate workflow

### PR DESCRIPTION
**Pull request by mcwarman**
Was looking at this project to better understand policies, noticed the validate CI was failing.

### CODE REVIEW

**Comment by mcwarman** [comment]
@olblak Fix wasn't as simple as I thought.

Although in hindsight makes sense as the token will only be scoped for this repo. 

Can use a GitHub App, if all the repos are in `updatecli` organisation, using `tibdex/github-app-token` probably want a readonly one so there's no chance of something happening unexpectedly.

**Comment by olblak** [comment]
> Can use a GitHub App, if all the repos are in `updatecli` organisation, using `tibdex/github-app-token` probably want a readonly one so there's no chance of something happening unexpectedly.

The goal of this repository is not to update all Updatecli organization but instead having "generic" policies that I can reuse.
I need to be sure that each policies on this repository are generic, and only specific to Updatecli in the testdata because I have some left overs 
This is part of an experimentation I worked on last week around Updatecli policies.

For example this [policy source code](https://github.com/updatecli/policies/tree/main/updatecli/policies/hugo/githubaction) is published on https://github.com/updatecli/policies/pkgs/container/policies%2Fpolicies%2Fhugo%2Fgithubaction

**Comment by olblak** [comment]
Something worth mentioning, I enabled branch protection this morning so I am planning now to push everything through pullrequest.
I have a few changes locally that I can now push since the latest Updatecli version is available

**Comment by olblak** [comment]
Thanks for your pullrequest :)

**Comment by mcwarman** [comment]
Understood, my comment was actually in reference to the e2e tests them selves as they're still failing because the the token set here:

https://github.com/updatecli/policies/blob/02e54712f57066fd4c59a263fef0ebb9178c83d6/.github/workflows/validate.yaml#L31

Won't be able to run the e2e tests, which is why I was suggesting a readonly one of some kind so the e2e tests had a chance to run.

**Comment by olblak** [comment]
I don't think the problem is coming from the token but how I designed the scm policies... (I just realize now)
Which can't work... :D 

Let me explain

**Comment by olblak** [comment]
I wanted to make a policy that would work differently if we run locally or from a CI environment.
If we detect some CI env variables, then we use those information otherwise we fallback to the values defined in the values.yaml

For that I am leveraging the default function in go template such as [here](https://github.com/updatecli/policies/blob/02e54712f57066fd4c59a263fef0ebb9178c83d6/updatecli/policies/hugo/githubaction/updatecli.d/manifest.yaml#L33)

This means that now all policies are  being tested against "github.com/updatecli/policies" instead of the values specified in testdata

**Comment by olblak** [comment]
I think to make the pass, I need to refactor all policies to not rely on env variable excepted the GITHUB_TOKEN

**Comment by olblak** [comment]
For info I opened https://github.com/updatecli/policies/issues/5

**Pull request merged**
