### PR TITLE
feat: opt-out scm.email

### PR DESCRIPTION
**Pull request by v1v**
requires bump the version in the Policy.yaml

Fix #XXX

[Documentation](https://)

## Description

Similarly done in https://github.com/updatecli/policies/pull/32 but in this case to all the policies

## Test

To test this pull request, you can run the following commands:

```shell
cp <to_package_directory>
go test
```

### CODE REVIEW

**Comment by v1v** [comment]
Requires https://github.com/updatecli/policies/pull/35

**Comment by olblak** [comment]
@v1v is this pullrequest still in draft?

**Comment by v1v** [comment]
> @v1v is this pullrequest still in draft?

@olblak , not anymore :)

**Comment by olblak** [comment]
> > @v1v is this pullrequest still in draft?
> 
> @olblak , not anymore :)

Thanks, I added a check to detect when the version in Policy.yaml hasn't been update according the CHANGELOG.md and then updated the missing version

**Review by olblak — APPROVED** [review]

**Pull request merged**
